[package]
name = "egoroff"
version = "0.1.0"
edition = "2021"
workspace = ".."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
kernel = { path = "../kernel" }
server = { path = "../server" }
migrate = { path = "../migrate", optional = true }
clap = { version = "4.2.5", features = ["std", "color", "suggestions", "cargo"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1", features = ["full"] }

mimalloc-rust = { version = "0.2", optional = true }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.5.0", optional = true }

[features]
migrating = ["migrate"]
mimalloc = ["mimalloc-rust"]
jemalloc = ["tikv-jemallocator"]