application: egoroff
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on
- deferred: on
- appstats: on

libraries:
- name: jinja2
  version: latest
- name: lxml
  version: "2.3"

handlers:
- url: /(favicon\.ico|robots\.txt)
  static_files: static/\1
  upload: static/(.*)

- url: /p/
  static_dir: static/
  expiration: 1000d

- url: /apache/images
  static_dir: apache/images

- url: /apache/css
  static_dir: apache/css

- url: /.*
  script: main.app

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?.*\.bak$
- ^(.*/)?Icon\r
- ^lib/.*
- ^static/src/.*
- ^static/lib/.*
- ^static/dst/.*
