runtime: go115

inbound_services:
  - warmup

handlers:
- url: /p/min/style/images/
  static_dir: static/ext/jquery-ui-less/less/images/
  expiration: 1000d

- url: /p/ext/font-awesome/fonts/
  static_dir: static/fonts/font-awesome/
  expiration: 1000d

- url: /p/ext/bootstrap/fonts/
  static_dir: static/fonts/bootstrap/
  expiration: 1000d

- url: /p/
  static_dir: static/

- url: /apache/images
  static_dir: apache/images

- url: /(robots\.txt|googlee53c87e9e3e91020\.html)
  static_files: static/\1
  upload: static/(.*)

- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /.*
  script: auto