runtime: go116

handlers:
- url: /css/
  static_dir: static/dist/css/

- url: /js/
  static_dir: static/dist/js/

- url: /apache/images
  static_dir: apache/images

- url: /(robots\.txt|googlee53c87e9e3e91020\.html)
  static_files: static/\1
  upload: static/(.*)

- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

env_variables:
  GIN_MODE: release