runtime: go115

handlers:
- url: /p/
  static_dir: static/

- url: /css/
  static_dir: static/dist/css/

- url: /js/
  static_dir: static/dist/js/

- url: /.well-known/pki-validation/
  static_dir: static/validation/

- url: /apache/images
  static_dir: apache/images

- url: /(robots\.txt|googlee53c87e9e3e91020\.html)
  static_files: static/\1
  upload: static/(.*)

- url: /favicon.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon.ico

- url: /.*
  script: auto

env_variables:
  GIN_MODE: release