name: PR

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Update rust
        run: rustup update
      - uses: actions/checkout@v4
      - name: Use Bun
        uses: oven-sh/setup-bun@v2
      - name: Install Dependencies
        working-directory: ./ui
        run: |
          bun install --frozen-lockfile
      - name: Bun Build
        working-directory: ./ui
        run: |
          bun run build
      - name: Install build deps
        run: |
          sudo apt-get update -y
          sudo apt-get install lld xsltproc jq -y
      - name: Build Apache docs
        run: |
          mkdir -p templates/apache
          jq -r '.[] | "\(.id) \(.stylesheet)"' apache/config.json | while read id xsl; do
            xsltproc --novalid -o templates/apache/$id.html apache/$xsl.xsl apache/$id.xml
          done
      - name: Rust Build
        run: cargo build --workspace
        working-directory: ./egoroff
      - name: Run tests
        run: cargo test --workspace
        working-directory: ./egoroff
